#!/bin/bash
# Task name
#SBATCH -J 3beam_correciton
# Run time limit
#SBATCH --time=8:00:00
# Working directory on shared storage
#SBATCH -D /lustre/nyx/panda/aali/prtdrc_2017/final_2017/workspace/testbeam/log
# Standard and error output in different files
#SBATCH -o %j_%N.out.log
#SBATCH -e %j_%N.err.log
# Execute application code



source /cvmfs/fairroot.gsi.de/fairsoft/may16_root5/bin/thisroot.sh
#source /lustre/nyx/panda/aali/prtdrc_2017/final_2017/workspace/install/root-6.08.06/bin/thisroot.sh
source /lustre/nyx/panda/aali/prtdrc_2017/final_2017/workspace/install/multi_thread_geant4/install/bin/geant4.sh
export LD_LIBRARY_PATH=/lustre/nyx/panda/aali/prtdrc_2017/final_2017/workspace/install/multi_thread_geant4/install/lib:$LD_LIBRARY_PATH
export PATH=/lustre/nyx/panda/aali/prtdrc_2017/final_2017/workspace/install/multi_thread_geant4/install/bin:$PATH
export PATH=/lustre/nyx/panda/aali/prtdrc_2017/final_2017/prttools/bin:$PATH




DIRr="/lustre/nyx/panda/aali/prtdrc_2017/final_2017/workspace/testbeam/recon/data/332/beam_correction_100"
DIRd="/lustre/nyx/panda/aali/prtdrc_2017/final_2017/workspace/testbeam/bardata/332/data"
DIRl="/lustre/nyx/panda/aali/prtdrc_2017/final_2017/workspace/testbeam/lut"

nevents=500000
cd /lustre/nyx/panda/aali/prtdrc_2017/final_2017/prtdirc/build


dtheta=$1
dphi=$2


recoAngle20_proton=0.818334
timeCut20_proton=1.842077
chAngleCut20_proton=0.045394
recoAngle30_proton=0.816051
timeCut30_proton=1.910087
chAngleCut30_proton=0.045984
recoAngle40_proton=0.816986
timeCut40_proton=1.889148
chAngleCut40_proton=0.050538
recoAngle50_proton=0.817087
timeCut50_proton=1.892745
chAngleCut50_proton=0.043855
recoAngle60_proton=0.815137
timeCut60_proton=1.895385
chAngleCut60_proton=0.047770
recoAngle70_proton=0.813078
timeCut70_proton=1.960066
chAngleCut70_proton=0.046759
recoAngle80_proton=0.812915
timeCut80_proton=2.091160
chAngleCut80_proton=0.047968
recoAngle90_proton=0.810881
timeCut90_proton=1.828611
chAngleCut90_proton=0.049158
recoAngle100_proton=0.811012
timeCut100_proton=1.395309
chAngleCut100_proton=0.038529
recoAngle110_proton=0.813848
timeCut110_proton=1.384700
chAngleCut110_proton=0.042495
recoAngle120_proton=0.814565
timeCut120_proton=1.377825
chAngleCut120_proton=0.047388
recoAngle130_proton=0.817052
timeCut130_proton=1.407649
chAngleCut130_proton=0.046720
recoAngle140_proton=0.816796
timeCut140_proton=1.441139
chAngleCut140_proton=0.050637
recoAngle150_proton=0.815613
timeCut150_proton=1.527406
chAngleCut150_proton=0.045013
############################
recoAngle20_pi=0.826920
timeCut20_pi=1.863995
chAngleCut20_pi=0.047589
recoAngle30_pi=0.824533
timeCut30_pi=1.901147
chAngleCut30_pi=0.049349
recoAngle40_pi=0.825388
timeCut40_pi=1.877434
chAngleCut40_pi=0.054559
recoAngle50_pi=0.824601
timeCut50_pi=1.880113
chAngleCut50_pi=0.044268
recoAngle60_pi=0.823733
timeCut60_pi=1.886543
chAngleCut60_pi=0.049438
recoAngle70_pi=0.820671
timeCut70_pi=1.931819
chAngleCut70_pi=0.044584
recoAngle80_pi=0.820424
timeCut80_pi=2.088451
chAngleCut80_pi=0.050023
recoAngle90_pi=0.819132
timeCut90_pi=1.794568
chAngleCut90_pi=0.048559
recoAngle100_pi=0.820097
timeCut100_pi=1.395242
chAngleCut100_pi=0.045446
recoAngle110_pi=0.821585
timeCut110_pi=1.371660
chAngleCut110_pi=0.040614
recoAngle120_pi=0.822756
timeCut120_pi=1.385644
chAngleCut120_pi=0.051380
recoAngle130_pi=0.824813
timeCut130_pi=1.403864
chAngleCut130_pi=0.045468
recoAngle140_pi=0.825208
timeCut140_pi=1.440179
chAngleCut140_pi=0.049217
recoAngle150_pi=0.823934
timeCut150_pi=1.521143
chAngleCut150_pi=0.048570


#./prtdirc -s 2 -i "${DIRd}/beam_s332_150C.root" -u "${DIRl}/lut_db_332_2018_cs_avr.root" -o "${DIRr}/db_150_3sph_t1_${dtheta}_t2_${dphi}_proton_data.root" -e $nevents -v 2 -tr $timeCut150_proton -chcut $chAngleCut150_proton -recoangle $recoAngle150_proton  -t1 $dtheta -t2 $dphi
#./prtdirc -s 2 -i "${DIRd}/beam_s332_20C.root" -u "${DIRl}/lut_db_332_2018_cs_avr.root" -o "${DIRr}/db_20_3sph_t1_${dtheta}_t2_${dphi}_pi_data.root" -e $nevents -v 2 -tr $timeCut20_pi -chcut $chAngleCut20_pi -recoangle $recoAngle20_pi  -t1 $dtheta -t2 $dphi

#./prtdirc -s 2 -i "${DIRd}/beam_s332_20C.root" -u "${DIRl}/lut_db_332_2018_cs_avr.root" -o "${DIRr}/db_20_3sph_t1_${dtheta}_t2_${dphi}_proton_data_p_correction.root" -recop 1 -recopi 0  -e $nevents -v 2 -tr $timeCut20_proton -chcut $chAngleCut20_proton -recoangle $recoAngle20_proton -t1 $dtheta -t2 $dphi -openchcorr 1
#./prtdirc -s 2 -i "${DIRd}/beam_s332_20C.root" -u "${DIRl}/lut_db_332_2018_cs_avr.root" -o "${DIRr}/db_20_3sph_t1_${dtheta}_t2_${dphi}_pi_data_p_correction.root"     -recop 0 -recopi 1  -e $nevents -v 2 -tr $timeCut20_pi      -chcut $chAngleCut20_pi    -recoangle $recoAngle20_pi     -t1 $dtheta -t2 $dphi -openchcorr 1

#./prtdirc -s 2 -i "${DIRd}/beam_s332_20C.root" -u "${DIRl}/lut_db_332_2018_cs_avr.root" -o "${DIRr}/db_20_3sph_t1_${dtheta}_t2_${dphi}_proton_data_custom_correction.root" -recop 1 -recopi 0  -e $nevents -v 2 -tr $timeCut20_proton -chcut $chAngleCut20_proton -recoangle $recoAngle20_proton -t1 $dtheta -t2 $dphi -openchcorr 2
#./prtdirc -s 2 -i "${DIRd}/beam_s332_20C.root" -u "${DIRl}/lut_db_332_2018_cs_avr.root" -o "${DIRr}/db_20_3sph_t1_${dtheta}_t2_${dphi}_pi_data_custom_correction.root"     -recop 0 -recopi 1  -e $nevents -v 2 -tr $timeCut20_pi      -chcut $chAngleCut20_pi    -recoangle $recoAngle20_pi     -t1 $dtheta -t2 $dphi -openchcorr 2

# Mar 2018
#./prtdirc -s 2 -i "${DIRd}/beam_s332_100C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_100_3sph_t1_${dtheta}_t2_${dphi}_proton_data_p_correction.root" -recop 1 -recopi 0  -e $nevents -v 2 -tr $timeCut100_proton -chcut $chAngleCut100_proton -recoangle $recoAngle100_proton -t1 $dtheta -t2 $dphi -openchcorr 1
#./prtdirc -s 2 -i "${DIRd}/beam_s332_100C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_100_3sph_t1_${dtheta}_t2_${dphi}_pi_data_p_correction.root"     -recop 0 -recopi 1  -e $nevents -v 2 -tr $timeCut100_proton -chcut $chAngleCut100_proton -recoangle $recoAngle100_proton -t1 $dtheta -t2 $dphi -openchcorr 1
#./prtdirc -s 2 -i "${DIRd}/beam_s332_100C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_100_3sph_t1_${dtheta}_t2_${dphi}_pi_data_pi_correction.root"    -recop 0 -recopi 1  -e $nevents -v 2 -tr $timeCut100_proton -chcut $chAngleCut100_proton -recoangle $recoAngle100_proton -t1 $dtheta -t2 $dphi -openchcorr 2
#./prtdirc -s 2 -i "${DIRd}/beam_s332_100C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_100_3sph_t1_${dtheta}_t2_${dphi}_proton_data_wo_correction.root" -recop 1 -recopi 0  -e $nevents -v 2 -tr $timeCut100_proton -chcut $chAngleCut100_proton -recoangle $recoAngle100_proton -t1 $dtheta -t2 $dphi -openchcorr 0
#./prtdirc -s 2 -i "${DIRd}/beam_s332_100C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_100_3sph_t1_${dtheta}_t2_${dphi}_pi_data_wo_correction.root"     -recop 0 -recopi 1  -e $nevents -v 2 -tr $timeCut100_proton -chcut $chAngleCut100_proton -recoangle $recoAngle100_proton -t1 $dtheta -t2 $dphi -openchcorr 0



#./prtdirc -s 2 -i "${DIRd}/beam_s332_110C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_110_3sph_t1_${dtheta}_t2_${dphi}_proton_data_p_correction.root" -recop 1 -recopi 0  -e $nevents -v 2 -tr $timeCut110_proton -chcut $chAngleCut110_proton -recoangle $recoAngle110_proton -t1 $dtheta -t2 $dphi -openchcorr 1
#./prtdirc -s 2 -i "${DIRd}/beam_s332_110C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_110_3sph_t1_${dtheta}_t2_${dphi}_pi_data_p_correction.root"     -recop 0 -recopi 1  -e $nevents -v 2 -tr $timeCut110_proton -chcut $chAngleCut110_proton -recoangle $recoAngle110_proton -t1 $dtheta -t2 $dphi -openchcorr 1
#./prtdirc -s 2 -i "${DIRd}/beam_s332_110C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_110_3sph_t1_${dtheta}_t2_${dphi}_pi_data_pi_correction.root"    -recop 0 -recopi 1  -e $nevents -v 2 -tr $timeCut110_proton -chcut $chAngleCut110_proton -recoangle $recoAngle110_proton -t1 $dtheta -t2 $dphi -openchcorr 2
#./prtdirc -s 2 -i "${DIRd}/beam_s332_110C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_110_3sph_t1_${dtheta}_t2_${dphi}_proton_data_wo_correction.root" -recop 1 -recopi 0  -e $nevents -v 2 -tr $timeCut110_proton -chcut $chAngleCut110_proton -recoangle $recoAngle110_proton -t1 $dtheta -t2 $dphi -openchcorr 0
#./prtdirc -s 2 -i "${DIRd}/beam_s332_110C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_110_3sph_t1_${dtheta}_t2_${dphi}_pi_data_wo_correction.root"     -recop 0 -recopi 1  -e $nevents -v 2 -tr $timeCut110_proton -chcut $chAngleCut110_proton -recoangle $recoAngle110_proton -t1 $dtheta -t2 $dphi -openchcorr 0




#./prtdirc -s 2 -i "${DIRd}/beam_s332_120C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_120_3sph_t1_${dtheta}_t2_${dphi}_proton_data_p_correction.root" -recop 1 -recopi 0  -e $nevents -v 2 -tr $timeCut120_proton -chcut $chAngleCut120_proton -recoangle $recoAngle120_proton -t1 $dtheta -t2 $dphi -openchcorr 1
#./prtdirc -s 2 -i "${DIRd}/beam_s332_120C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_120_3sph_t1_${dtheta}_t2_${dphi}_pi_data_p_correction.root"     -recop 0 -recopi 1  -e $nevents -v 2 -tr $timeCut120_proton -chcut $chAngleCut120_proton -recoangle $recoAngle120_proton -t1 $dtheta -t2 $dphi -openchcorr 1
#./prtdirc -s 2 -i "${DIRd}/beam_s332_120C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_120_3sph_t1_${dtheta}_t2_${dphi}_pi_data_pi_correction.root"    -recop 0 -recopi 1  -e $nevents -v 2 -tr $timeCut120_proton -chcut $chAngleCut120_proton -recoangle $recoAngle120_proton -t1 $dtheta -t2 $dphi -openchcorr 2
#./prtdirc -s 2 -i "${DIRd}/beam_s332_120C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_120_3sph_t1_${dtheta}_t2_${dphi}_proton_data_wo_correction.root" -recop 1 -recopi 0  -e $nevents -v 2 -tr $timeCut120_proton -chcut $chAngleCut120_proton -recoangle $recoAngle120_proton -t1 $dtheta -t2 $dphi -openchcorr 0
#./prtdirc -s 2 -i "${DIRd}/beam_s332_120C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_120_3sph_t1_${dtheta}_t2_${dphi}_pi_data_wo_correction.root"     -recop 0 -recopi 1  -e $nevents -v 2 -tr $timeCut120_proton -chcut $chAngleCut120_proton -recoangle $recoAngle120_proton -t1 $dtheta -t2 $dphi -openchcorr 0




#./prtdirc -s 2 -i "${DIRd}/beam_s332_130C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_130_3sph_t1_${dtheta}_t2_${dphi}_proton_data_p_correction.root" -recop 1 -recopi 0  -e $nevents -v 2 -tr $timeCut130_proton -chcut $chAngleCut130_proton -recoangle $recoAngle130_proton -t1 $dtheta -t2 $dphi -openchcorr 1
#./prtdirc -s 2 -i "${DIRd}/beam_s332_130C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_130_3sph_t1_${dtheta}_t2_${dphi}_pi_data_p_correction.root"     -recop 0 -recopi 1  -e $nevents -v 2 -tr $timeCut130_proton -chcut $chAngleCut130_proton -recoangle $recoAngle130_proton -t1 $dtheta -t2 $dphi -openchcorr 1
#./prtdirc -s 2 -i "${DIRd}/beam_s332_130C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_130_3sph_t1_${dtheta}_t2_${dphi}_pi_data_pi_correction.root"    -recop 0 -recopi 1  -e $nevents -v 2 -tr $timeCut130_proton -chcut $chAngleCut130_proton -recoangle $recoAngle130_proton -t1 $dtheta -t2 $dphi -openchcorr 2
#./prtdirc -s 2 -i "${DIRd}/beam_s332_130C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_130_3sph_t1_${dtheta}_t2_${dphi}_proton_data_wo_correction.root" -recop 1 -recopi 0  -e $nevents -v 2 -tr $timeCut130_proton -chcut $chAngleCut130_proton -recoangle $recoAngle130_proton -t1 $dtheta -t2 $dphi -openchcorr 0
#./prtdirc -s 2 -i "${DIRd}/beam_s332_130C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_130_3sph_t1_${dtheta}_t2_${dphi}_pi_data_wo_correction.root"     -recop 0 -recopi 1  -e $nevents -v 2 -tr $timeCut130_proton -chcut $chAngleCut130_proton -recoangle $recoAngle130_proton -t1 $dtheta -t2 $dphi -openchcorr 0




#./prtdirc -s 2 -i "${DIRd}/beam_s332_140C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_140_3sph_t1_${dtheta}_t2_${dphi}_proton_data_p_correction.root" -recop 1 -recopi 0  -e $nevents -v 2 -tr $timeCut140_proton -chcut $chAngleCut140_proton -recoangle $recoAngle140_proton -t1 $dtheta -t2 $dphi -openchcorr 1
#./prtdirc -s 2 -i "${DIRd}/beam_s332_140C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_140_3sph_t1_${dtheta}_t2_${dphi}_pi_data_p_correction.root"     -recop 0 -recopi 1  -e $nevents -v 2 -tr $timeCut140_proton -chcut $chAngleCut140_proton -recoangle $recoAngle140_proton -t1 $dtheta -t2 $dphi -openchcorr 1
#./prtdirc -s 2 -i "${DIRd}/beam_s332_140C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_140_3sph_t1_${dtheta}_t2_${dphi}_pi_data_pi_correction.root"    -recop 0 -recopi 1  -e $nevents -v 2 -tr $timeCut140_proton -chcut $chAngleCut140_proton -recoangle $recoAngle140_proton -t1 $dtheta -t2 $dphi -openchcorr 2
#./prtdirc -s 2 -i "${DIRd}/beam_s332_140C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_140_3sph_t1_${dtheta}_t2_${dphi}_proton_data_wo_correction.root" -recop 1 -recopi 0  -e $nevents -v 2 -tr $timeCut140_proton -chcut $chAngleCut140_proton -recoangle $recoAngle140_proton -t1 $dtheta -t2 $dphi -openchcorr 0
#./prtdirc -s 2 -i "${DIRd}/beam_s332_140C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_140_3sph_t1_${dtheta}_t2_${dphi}_pi_data_wo_correction.root"     -recop 0 -recopi 1  -e $nevents -v 2 -tr $timeCut140_proton -chcut $chAngleCut140_proton -recoangle $recoAngle140_proton -t1 $dtheta -t2 $dphi -openchcorr 0




#./prtdirc -s 2 -i "${DIRd}/beam_s332_150C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_150_3sph_t1_${dtheta}_t2_${dphi}_proton_data_p_correction.root" -recop 1 -recopi 0  -e $nevents -v 2 -tr $timeCut150_proton -chcut $chAngleCut150_proton -recoangle $recoAngle150_proton -t1 $dtheta -t2 $dphi -openchcorr 1
#./prtdirc -s 2 -i "${DIRd}/beam_s332_150C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_150_3sph_t1_${dtheta}_t2_${dphi}_pi_data_p_correction.root"     -recop 0 -recopi 1  -e $nevents -v 2 -tr $timeCut150_proton -chcut $chAngleCut150_proton -recoangle $recoAngle150_proton -t1 $dtheta -t2 $dphi -openchcorr 1
#./prtdirc -s 2 -i "${DIRd}/beam_s332_150C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_150_3sph_t1_${dtheta}_t2_${dphi}_pi_data_pi_correction.root"    -recop 0 -recopi 1  -e $nevents -v 2 -tr $timeCut150_proton -chcut $chAngleCut150_proton -recoangle $recoAngle150_proton -t1 $dtheta -t2 $dphi -openchcorr 2
#./prtdirc -s 2 -i "${DIRd}/beam_s332_150C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_150_3sph_t1_${dtheta}_t2_${dphi}_proton_data_wo_correction.root" -recop 1 -recopi 0  -e $nevents -v 2 -tr $timeCut150_proton -chcut $chAngleCut150_proton -recoangle $recoAngle150_proton -t1 $dtheta -t2 $dphi -openchcorr 0
#./prtdirc -s 2 -i "${DIRd}/beam_s332_150C.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRr}/opt_150_3sph_t1_${dtheta}_t2_${dphi}_pi_data_wo_correction.root"     -recop 0 -recopi 1  -e $nevents -v 2 -tr $timeCut150_proton -chcut $chAngleCut150_proton -recoangle $recoAngle150_proton -t1 $dtheta -t2 $dphi -openchcorr 0







