#!/bin/bash

root -b -q ../cherenkov_angle_correction.C'(0,20)'
root -b -q ../cherenkov_angle_correction.C'(0,30)'
root -b -q ../cherenkov_angle_correction.C'(0,40)'
root -b -q ../cherenkov_angle_correction.C'(0,50)'
root -b -q ../cherenkov_angle_correction.C'(0,60)'
root -b -q ../cherenkov_angle_correction.C'(0,70)'
root -b -q ../cherenkov_angle_correction.C'(0,80)'
root -b -q ../cherenkov_angle_correction.C'(0,90)'
root -b -q ../cherenkov_angle_correction.C'(0,100)'
root -b -q ../cherenkov_angle_correction.C'(0,110)'
root -b -q ../cherenkov_angle_correction.C'(0,120)'
root -b -q ../cherenkov_angle_correction.C'(0,130)'
root -b -q ../cherenkov_angle_correction.C'(0,140)'
root -b -q ../cherenkov_angle_correction.C'(0,150)'

root -b -q ../cherenkov_angle_correction.C'(1,20)'
root -b -q ../cherenkov_angle_correction.C'(1,30)'
root -b -q ../cherenkov_angle_correction.C'(1,40)'
root -b -q ../cherenkov_angle_correction.C'(1,50)'
root -b -q ../cherenkov_angle_correction.C'(1,60)'
root -b -q ../cherenkov_angle_correction.C'(1,70)'
root -b -q ../cherenkov_angle_correction.C'(1,80)'
root -b -q ../cherenkov_angle_correction.C'(1,90)'
root -b -q ../cherenkov_angle_correction.C'(1,100)'
root -b -q ../cherenkov_angle_correction.C'(1,110)'
root -b -q ../cherenkov_angle_correction.C'(1,120)'
root -b -q ../cherenkov_angle_correction.C'(1,130)'
root -b -q ../cherenkov_angle_correction.C'(1,140)'
root -b -q ../cherenkov_angle_correction.C'(1,150)'
