#!/bin/bash
# Task name
#SBATCH -J reco_error_sample
# Run time limit
#SBATCH --time=8:00:00
# Working directory on shared storage
#SBATCH -D /lustre/nyx/panda/aali/prtdrc_2017/final_2017/workspace/testbeam/log
# Standard and error output in different files
#SBATCH -o %j_%N.out.log
#SBATCH -e %j_%N.err.log
# Execute application code


source /cvmfs/fairroot.gsi.de/fairsoft/may16_root5/bin/thisroot.sh
source /lustre/nyx/panda/aali/prtdrc_2017/final_2017/workspace/install/multi_thread_geant4/install/bin/geant4.sh
export LD_LIBRARY_PATH=/lustre/nyx/panda/aali/prtdrc_2017/final_2017/workspace/install/multi_thread_geant4/install/lib:$LD_LIBRARY_PATH
export PATH=/lustre/nyx/panda/aali/prtdrc_2017/final_2017/workspace/install/multi_thread_geant4/install/bin:$PATH
export PATH=/lustre/nyx/panda/aali/prtdrc_2017/final_2017/prttools/bin:$PATH


DIRs="/lustre/nyx/panda/aali/prtdrc_2017/final_2017/workspace/testbeam/sim/332"
DIRl="/lustre/nyx/panda/aali/prtdrc_2017/final_2017/workspace/testbeam/lut"

cd /lustre/nyx/panda/aali/prtdrc_2017/final_2017/prtdirc/build
nevents=5000

#####################
# Normal Simulations#
#####################
# Run batch_sim.sh
#t=$1
#recoAngle_p=$2
#recoAngle_pi=$3

# step(1) simulation 
#./prtdirc -a $t -l 3 -x "proton" -p 7 -w 0 -g 2017 -e $nevents -h 1 -c 2017 -gz 447 -gx 89.85 -gsx 70 -gsy 0 -o "${DIRs}/check_theta_${t}_3lsph_proton_sim.root" -r 0 -tr 0 -b 1
#./prtdirc -a $t -l 3 -x "pi+" -p 7 -w 0 -g 2017 -e $nevents -h 1 -c 2017 -gz 447 -gx 89.85 -gsx 70 -gsy 0 -o "${DIRs}/check_theta_${t}_3lsph_pi_sim.root" -r 0 -tr 0 -b 1

#./prtdirc -s 2 -i "${DIRs}/check_theta_${t}_3lsph_proton_sim.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRs}/spr_check_theta_${t}_3lsph_proton_sim.root" -e 0 -v 2 -gpdf 0 -tr 5.0 -chcut 5.0 -recoangle $recoAngle_p  -recop 1 -recopi 0 -openchcorr 2
#./prtdirc -s 2 -i "${DIRs}/check_theta_${t}_3lsph_pi_sim.root"     -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRs}/spr_check_theta_${t}_3lsph_pi_sim.root"     -e 0 -v 2 -gpdf 0 -tr 5.0 -chcut 5.0 -recoangle $recoAngle_pi  -recop 0 -recopi 1 -openchcorr 2


#./prtdirc -a $t -l 3 -x "proton" -p 7 -w 0 -g 2017 -e $nevents -h 1 -c 2017 -gsx 67 -gsy 14.7 -gx 89.85 -gz 447 -o "${DIRs}/forPDF_theta_${t}_3lsph_proton_sim.root" -r 0 -tr 0 -b 1 -r 890136
#./prtdirc -a $t -l 3 -x "pi+"    -p 7 -w 0 -g 2017 -e $nevents -h 1 -c 2017 -gsx 67 -gsy 14.7 -gx 89.85 -gz 447 -o "${DIRs}/forPDF_theta_${t}_3lsph_pi_sim.root" -r 0 -tr 0 -b 1 -r 890136



#######################################
# Eror Calc. for Polar angle variation#
#######################################
# Run batch_polar_error_sim.sh

#t=$1
#recoAngle_p=$2
#recoAngle_pi=$3

# polar angle variation simulation (step 1)
#./prtdirc -a $t -l 3 -x "proton" -p 7 -w 0 -g 2017 -e $nevents -h 1 -c 2017 -gsx 67 -gsy 14.7 -gx 89.85 -gz 447 -o "${DIRs}/polar_error_theta_${t}_3lsph_proton_sim.root" -r 0 -tr 0 -b 1 -r 0
#./prtdirc -a $t -l 3 -x "pi+"    -p 7 -w 0 -g 2017 -e $nevents -h 1 -c 2017 -gsx 67 -gsy 14.7 -gx 89.85 -gz 447 -o "${DIRs}/polar_error_theta_${t}_3lsph_pi_sim.root" -r 0 -tr 0 -b 1 -r 0

# polar angle variation  Reco. step 2
#./prtdirc -s 2 -i "${DIRs}/polar_error_theta_${t}_3lsph_proton_sim.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRs}/spr_polar_error_theta_${t}_3lsph_proton_sim.root" -e 0 -v 2 -gpdf 0 -tr 5.0 -chcut 5.0 -recoangle $recoAngle_p  -recop 1 -recopi 0 -openchcorr 2
#./prtdirc -s 2 -i "${DIRs}/polar_error_theta_${t}_3lsph_pi_sim.root"     -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRs}/spr_polar_error_theta_${t}_3lsph_pi_sim.root"     -e 0 -v 2 -gpdf 0 -tr 5.0 -chcut 5.0 -recoangle $recoAngle_pi  -recop 0 -recopi 1 -openchcorr 2


##########################################
# Eror Calc. for sample MC seed variation#
##########################################
# Run batch_stat_error_sim.sh

#t=$1
#recoAngle_p=$2
#recoAngle_pi=$3
#k=$4

#Sim Step 1
#./prtdirc -a $t -l 3 -x "proton" -p 7 -w 0 -g 2017 -e $nevents -h 1 -c 2017 -gsx 67 -gsy 14.7 -gx 89.85 -gz 447 -o "${DIRs}/statistics_error_theta_${t}_seed_${k}_3lsph_proton_sim.root" -tr 0 -b 1 -r $k
#./prtdirc -a $t -l 3 -x "pi+"    -p 7 -w 0 -g 2017 -e $nevents -h 1 -c 2017 -gsx 67 -gsy 14.7 -gx 89.85 -gz 447 -o "${DIRs}/statistics_error_theta_${t}_seed_${k}_3lsph_pi_sim.root" -tr 0 -b 1 -r $k

# Reco Step 2
#./prtdirc -s 2 -i "${DIRs}/statistics_error_theta_${t}_seed_${k}_3lsph_proton_sim.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRs}/statistics_error_theta_${t}_seed_${k}_3lsph_proton_sim.root" -e 0 -v 2 -gpdf 0 -tr 5.0 -chcut 5.0 -recoangle $recoAngle_p  -recop 1 -recopi 0 -openchcorr 2
#./prtdirc -s 2 -i "${DIRs}/statistics_error_theta_${t}_seed_${k}_3lsph_pi_sim.root"     -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRs}/statistics_error_theta_${t}_seed_${k}_3lsph_pi_sim.root"     -e 0 -v 2 -gpdf 0 -tr 5.0 -chcut 5.0 -recoangle $recoAngle_pi  -recop 0 -recopi 1 -openchcorr 2

##############################################
# Eror Calc. for Delta t cut and theta c cut #
##############################################
# Run batch_tccuts_error_sim.sh

t=$1
recoAngle_p=$2
recoAngle_pi=$3
k=$4

./prtdirc -a $t -l 3 -x "proton" -p 7 -w 0 -g 2017 -e $nevents -h 1 -c 2017 -gz 447 -gx 89.85 -gsx 70 -gsy 0 -o "${DIRs}/theta_${t}_3lsph_proton_sim.root" -r 0 -tr 0 -b 1
./prtdirc -a $t -l 3 -x "pi+" -p 7 -w 0 -g 2017 -e $nevents -h 1 -c 2017 -gz 447 -gx 89.85 -gsx 70 -gsy 0 -o "${DIRs}/theta_${t}_3lsph_pi_sim.root" -r 0 -tr 0 -b 1

# Reco Step t cut
./prtdirc -s 2 -i "${DIRs}/theta_${t}_3lsph_proton_sim.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRs}/tcut_error_theta_${t}_seed_${k}_3lsph_proton_sim.root" -e 0 -v 2 -gpdf 0 -tr $k -chcut 5.0 -recoangle $recoAngle_p  -recop 1 -recopi 0 -openchcorr 2
./prtdirc -s 2 -i "${DIRs}/theta_${t}_3lsph_pi_sim.root"     -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRs}/tcut_error_theta_${t}_seed_${k}_3lsph_pi_sim.root"     -e 0 -v 2 -gpdf 0 -tr $k -chcut 5.0 -recoangle $recoAngle_pi  -recop 0 -recopi 1 -openchcorr 2

# Reco Step theta c cut
./prtdirc -s 2 -i "${DIRs}/theta_${t}_3lsph_proton_sim.root" -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRs}/ccut_error_theta_${t}_seed_${k}_3lsph_proton_sim.root" -e 0 -v 2 -gpdf 0 -tr 5.0 -chcut $k -recoangle $recoAngle_p  -recop 1 -recopi 0 -openchcorr 2
./prtdirc -s 2 -i "${DIRs}/theta_${t}_3lsph_pi_sim.root"     -u "${DIRl}/lut_opt_332_2018_cs_avr.root" -o "${DIRs}/ccut_error_theta_${t}_seed_${k}_3lsph_pi_sim.root"     -e 0 -v 2 -gpdf 0 -tr 5.0 -chcut $k -recoangle $recoAngle_pi  -recop 0 -recopi 1 -openchcorr 2

##########################################
#X step= 67 mm
#Y step= 14.7 mm

#hadd "${DIRs}/theta_${t}_3lsph_all_sim.root" "${DIRs}/theta_${t}_3lsph_proton_sim.root" "${DIRs}/theta_${t}_3lsph_pi_sim.root"
